// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVpko8OGnMv-Q1dO6PLhh5m2Kfi9wX36M',
    appId: '1:533217486566:web:0586b04d10cef5201e7d27',
    messagingSenderId: '533217486566',
    projectId: 'cookhelper-fa428',
    authDomain: 'cookhelper-fa428.firebaseapp.com',
    storageBucket: 'cookhelper-fa428.appspot.com',
    measurementId: 'G-9L0C36Q787',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLkgNB9GdKMFVpOLCJ-_6vaAoZSjl0kao',
    appId: '1:533217486566:android:50adcc41399936351e7d27',
    messagingSenderId: '533217486566',
    projectId: 'cookhelper-fa428',
    storageBucket: 'cookhelper-fa428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArWbo8XGK2LbfCJ42QDgeZMhzC9-r3TaI',
    appId: '1:533217486566:ios:2edba40c488d2a051e7d27',
    messagingSenderId: '533217486566',
    projectId: 'cookhelper-fa428',
    storageBucket: 'cookhelper-fa428.appspot.com',
    iosClientId: '533217486566-t777eulj33i2pvi44n03ipdko98l0n0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArWbo8XGK2LbfCJ42QDgeZMhzC9-r3TaI',
    appId: '1:533217486566:ios:2edba40c488d2a051e7d27',
    messagingSenderId: '533217486566',
    projectId: 'cookhelper-fa428',
    storageBucket: 'cookhelper-fa428.appspot.com',
    iosClientId: '533217486566-t777eulj33i2pvi44n03ipdko98l0n0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookHelper',
  );
}
